package org.example.fanshop.entity.enums;

public enum ClubRole {
    FOOTBALLER,
    CLUB_PRESIDENT,
    DIRECTOR_OF_FOOTBALL,
    SPORTING_DIRECTOR,
    HEAD_COACH,
    ASSISTANT_COACH,
    GOALKEEPING_COACH,
    FITNESS_COACH,
    PHYSIOTHERAPIST,
    TEAM_DOCTOR,
    SCOUT,
    ANALYST,
    CLUB_SECRETARY,
    MEDIA_OFFICER,
    MARKETING_MANAGER,
    ACADEMY_DIRECTOR,
    KIT_MANAGER
}
